-- ============================================================
-- PME CARBONITA 2026-2036
-- Supabase + autenticação + RLS por instituição
-- Execute no SQL Editor do Supabase.
-- Este script também substitui as permissões anônimas do SQL anterior.
-- ============================================================

begin;

-- 1) PERFIS DE ACESSO
create table if not exists public.pme_usuarios (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  role text not null check (role in ('admin', 'instituicao')),
  institution_id text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pme_usuarios_institution_check check (
    (role = 'admin' and institution_id is null)
    or
    (role = 'instituicao' and institution_id is not null)
  )
);

-- 2) RELATÓRIOS
create table if not exists public.pme_relatorios (
  id bigint generated by default as identity primary key,
  institution_id text not null,
  institution_name text not null,
  institution_category text,
  responsible text,
  reference_date date not null default current_date,
  status text not null default 'Em preenchimento'
    check (status in ('Em preenchimento', 'Concluído')),
  completed_fields integer not null default 0 check (completed_fields >= 0),
  total_fields integer not null default 0 check (total_fields >= 0),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (completed_fields <= total_fields)
);

-- Se a tabela já existia do SQL anterior, adiciona created_by sem destruir dados.
alter table public.pme_relatorios
  add column if not exists created_by uuid references auth.users(id) on delete set null default auth.uid();

-- 3) RESPOSTAS
create table if not exists public.pme_respostas (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.pme_relatorios(id) on delete cascade,
  institution_id text not null,
  field_id text not null,
  field_group text,
  question text not null,
  answer text not null default '',
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pme_respostas_report_field_unique unique (report_id, field_id)
);

-- 4) ÍNDICES
create index if not exists pme_usuarios_institution_idx on public.pme_usuarios (institution_id);
create index if not exists pme_relatorios_institution_idx on public.pme_relatorios (institution_id);
create index if not exists pme_relatorios_created_by_idx on public.pme_relatorios (created_by);
create index if not exists pme_relatorios_reference_date_idx on public.pme_relatorios (reference_date);
create index if not exists pme_relatorios_updated_at_idx on public.pme_relatorios (updated_at desc);
create index if not exists pme_respostas_report_id_idx on public.pme_respostas (report_id);
create index if not exists pme_respostas_institution_idx on public.pme_respostas (institution_id);

-- 5) UPDATED_AT AUTOMÁTICO
create or replace function public.pme_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pme_usuarios_set_updated_at on public.pme_usuarios;
create trigger pme_usuarios_set_updated_at
before update on public.pme_usuarios
for each row execute function public.pme_set_updated_at();

drop trigger if exists pme_relatorios_set_updated_at on public.pme_relatorios;
create trigger pme_relatorios_set_updated_at
before update on public.pme_relatorios
for each row execute function public.pme_set_updated_at();

drop trigger if exists pme_respostas_set_updated_at on public.pme_respostas;
create trigger pme_respostas_set_updated_at
before update on public.pme_respostas
for each row execute function public.pme_set_updated_at();

-- 6) FUNÇÕES DE AUTORIZAÇÃO
create or replace function public.pme_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select u.active and u.role = 'admin'
    from public.pme_usuarios u
    where u.user_id = auth.uid()
    limit 1
  ), false);
$$;

create or replace function public.pme_current_institution()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select u.institution_id
  from public.pme_usuarios u
  where u.user_id = auth.uid()
    and u.active = true
    and u.role = 'instituicao'
  limit 1;
$$;

create or replace function public.pme_can_access_report(target_report_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.pme_relatorios r
    where r.id = target_report_id
      and (
        public.pme_is_admin()
        or r.institution_id = public.pme_current_institution()
      )
  );
$$;

revoke all on function public.pme_is_admin() from public;
revoke all on function public.pme_current_institution() from public;
revoke all on function public.pme_can_access_report(bigint) from public;
grant execute on function public.pme_is_admin() to authenticated;
grant execute on function public.pme_current_institution() to authenticated;
grant execute on function public.pme_can_access_report(bigint) to authenticated;

-- 7) RLS
alter table public.pme_usuarios enable row level security;
alter table public.pme_relatorios enable row level security;
alter table public.pme_respostas enable row level security;

-- Remove TODAS as policies anteriores dessas três tabelas para evitar acesso anon antigo.
do $$
declare p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('pme_usuarios', 'pme_relatorios', 'pme_respostas')
  loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

-- Perfis: usuário lê o próprio perfil; admin lê todos.
create policy "PME usuarios select"
on public.pme_usuarios
for select
to authenticated
using ((select auth.uid()) = user_id or public.pme_is_admin());

create policy "PME usuarios insert admin"
on public.pme_usuarios
for insert
to authenticated
with check (public.pme_is_admin());

create policy "PME usuarios update admin"
on public.pme_usuarios
for update
to authenticated
using (public.pme_is_admin())
with check (public.pme_is_admin());

create policy "PME usuarios delete admin"
on public.pme_usuarios
for delete
to authenticated
using (public.pme_is_admin());

-- Relatórios: admin vê tudo; instituição só vê sua própria instituição.
create policy "PME relatorios select"
on public.pme_relatorios
for select
to authenticated
using (
  public.pme_is_admin()
  or institution_id = public.pme_current_institution()
);

create policy "PME relatorios insert"
on public.pme_relatorios
for insert
to authenticated
with check (
  public.pme_is_admin()
  or (
    institution_id = public.pme_current_institution()
    and created_by = (select auth.uid())
  )
);

create policy "PME relatorios update"
on public.pme_relatorios
for update
to authenticated
using (
  public.pme_is_admin()
  or institution_id = public.pme_current_institution()
)
with check (
  public.pme_is_admin()
  or institution_id = public.pme_current_institution()
);

create policy "PME relatorios delete"
on public.pme_relatorios
for delete
to authenticated
using (
  public.pme_is_admin()
  or institution_id = public.pme_current_institution()
);

-- Respostas seguem o acesso do relatório pai.
create policy "PME respostas select"
on public.pme_respostas
for select
to authenticated
using (public.pme_can_access_report(report_id));

create policy "PME respostas insert"
on public.pme_respostas
for insert
to authenticated
with check (
  public.pme_can_access_report(report_id)
  and (
    public.pme_is_admin()
    or institution_id = public.pme_current_institution()
  )
);

create policy "PME respostas update"
on public.pme_respostas
for update
to authenticated
using (public.pme_can_access_report(report_id))
with check (
  public.pme_can_access_report(report_id)
  and (
    public.pme_is_admin()
    or institution_id = public.pme_current_institution()
  )
);

create policy "PME respostas delete"
on public.pme_respostas
for delete
to authenticated
using (public.pme_can_access_report(report_id));

-- 8) PRIVILÉGIOS: nenhum acesso de dados sem login.
revoke all on table public.pme_usuarios from anon;
revoke all on table public.pme_relatorios from anon;
revoke all on table public.pme_respostas from anon;

grant select, insert, update, delete on table public.pme_usuarios to authenticated;
grant select, insert, update, delete on table public.pme_relatorios to authenticated;
grant select, insert, update, delete on table public.pme_respostas to authenticated;

grant usage, select on sequence public.pme_relatorios_id_seq to authenticated;
grant usage, select on sequence public.pme_respostas_id_seq to authenticated;

-- 9) VIEW PARA EXCEL / POWER BI
create or replace view public.pme_base_powerbi
with (security_invoker = true)
as
select
  r.id as relatorio_id,
  r.institution_id as instituicao_id,
  r.institution_name as instituicao,
  r.institution_category as categoria,
  r.responsible as responsavel,
  r.reference_date as data_referencia,
  r.status,
  r.completed_fields as campos_preenchidos,
  r.total_fields as total_campos,
  case
    when r.total_fields > 0
      then round((r.completed_fields::numeric / r.total_fields::numeric) * 100, 2)
    else 0
  end as percentual_preenchimento,
  a.field_group as grupo,
  a.sort_order as ordem,
  a.field_id as campo_id,
  a.question as pergunta,
  a.answer as resposta,
  r.created_by as criado_por,
  r.created_at as relatorio_criado_em,
  r.updated_at as relatorio_atualizado_em,
  a.updated_at as resposta_atualizada_em
from public.pme_relatorios r
join public.pme_respostas a on a.report_id = r.id;

revoke all on public.pme_base_powerbi from anon;
grant select on public.pme_base_powerbi to authenticated;

commit;

-- ============================================================
-- CRIAÇÃO DOS USUÁRIOS
-- ============================================================
-- 1. Primeiro crie a conta em Authentication > Users no painel do Supabase.
-- 2. Depois use UM dos exemplos abaixo, trocando o e-mail e o nome.
--
-- ADMINISTRAÇÃO DO PME:
-- insert into public.pme_usuarios (user_id, nome, role, institution_id)
-- select id, 'Coordenação do PME', 'admin', null
-- from auth.users
-- where email = 'admin@exemplo.com'
-- on conflict (user_id) do update
-- set nome = excluded.nome, role = excluded.role, institution_id = excluded.institution_id, active = true;
--
-- SECRETARIA MUNICIPAL DE SAÚDE:
-- insert into public.pme_usuarios (user_id, nome, role, institution_id)
-- select id, 'Secretaria Municipal de Saúde', 'instituicao', 'saude'
-- from auth.users
-- where email = 'saude@exemplo.com'
-- on conflict (user_id) do update
-- set nome = excluded.nome, role = excluded.role, institution_id = excluded.institution_id, active = true;
--
-- IDs de instituição usados pelo sistema:
-- saude
-- assistencia-social
-- fazenda
-- coronel-coimbra
-- mestra-aurora
-- ifnmg
-- cruzeiro-do-sul
-- ============================================================
